"""
Django settings for citas_medicas project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR es la ruta base del proyecto, se utiliza para construir rutas relativas
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+e3*bkc13-4b+(b1$avbit-cnnyx#lzt(8jduurvrh!d6rfzoz'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Definición de aplicaciones instaladas
# Lista de aplicaciones Django que están habilitadas en este proyecto
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'usuarios',  # Nuestra aplicación personalizada para gestión de usuarios
]

# Middleware - Componentes que procesan las solicitudes/respuestas
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Configuración principal de URLs
ROOT_URLCONF = 'citas_medicas.urls'  # Módulo que contiene las definiciones de URL raíz

# Configuración de plantillas
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Configuración de la aplicación WSGI para despliegue
WSGI_APPLICATION = 'citas_medicas.wsgi.application'


# Configuración de la base de datos
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# Se utiliza SQLite como base de datos por defecto para desarrollo
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Validadores de contraseñas
# Configuración para garantizar contraseñas seguras
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Configuración de internacionalización
# Permite la traducción y localización de la aplicación
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'  # Código de idioma predeterminado

TIME_ZONE = 'UTC'  # Zona horaria predeterminada

USE_I18N = True  # Habilita el sistema de internacionalización

USE_TZ = True  # Habilita el soporte de zona horaria


# Archivos estáticos (CSS, JavaScript, Imágenes)
# Configuración para servir archivos estáticos
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'  # URL base para acceder a los archivos estáticos
STATIC_ROOT = BASE_DIR / 'staticfiles'  # Directorio donde se recopilan los archivos estáticos para producción

# Directorios adicionales donde Django buscará archivos estáticos
STATICFILES_DIRS = [
    BASE_DIR / 'usuarios/static',  # Archivos estáticos de la aplicación usuarios
]

# Tipo de campo predeterminado para claves primarias
# Define el tipo de campo automático para las claves primarias en los modelos
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'  # Utiliza BigAutoField como tipo predeterminado
