# Generated by Django 5.2.4 on 2025-08-06 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Usuarios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                ("apellido", models.CharField(max_length=100, verbose_name="Apellido")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Correo Electrónico"
                    ),
                ),
                ("telefono", models.CharField(max_length=15, verbose_name="Teléfono")),
                (
                    "fecha_nacimiento",
                    models.DateField(verbose_name="Fecha de Nacimiento"),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            ("CC", "Cédula de Ciudadanía"),
                            ("TI", "Tarjeta de Identidad"),
                            ("CE", "Cédula de Extranjería"),
                            ("PP", "Pasaporte"),
                            ("RC", "Registro Civil"),
                        ],
                        default="CC",
                        max_length=2,
                        verbose_name="Tipo de Documento",
                    ),
                ),
                (
                    "cedula",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Número de Documento"
                    ),
                ),
                (
                    "genero",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("M", "Masculino"),
                            ("F", "Femenino"),
                            ("O", "Otro"),
                            ("N", "Prefiero no decir"),
                        ],
                        max_length=1,
                        null=True,
                        verbose_name="Género",
                    ),
                ),
                (
                    "tipo_sangre",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                            ("NS", "No sabe"),
                        ],
                        max_length=3,
                        null=True,
                        verbose_name="Tipo de Sangre",
                    ),
                ),
                (
                    "direccion",
                    models.TextField(blank=True, null=True, verbose_name="Dirección"),
                ),
                (
                    "contacto_emergencia_nombre",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Nombre Contacto de Emergencia",
                    ),
                ),
                (
                    "contacto_emergencia_telefono",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="Teléfono Contacto de Emergencia",
                    ),
                ),
                (
                    "contacto_emergencia_relacion",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Relación Contacto de Emergencia",
                    ),
                ),
                (
                    "alergias",
                    models.TextField(
                        blank=True,
                        help_text="Describa cualquier alergia conocida a medicamentos, alimentos, etc.",
                        null=True,
                        verbose_name="Alergias Conocidas",
                    ),
                ),
                (
                    "medicamentos_actuales",
                    models.TextField(
                        blank=True,
                        help_text="Liste los medicamentos que toma actualmente",
                        null=True,
                        verbose_name="Medicamentos Actuales",
                    ),
                ),
                (
                    "condiciones_medicas",
                    models.TextField(
                        blank=True,
                        help_text="Describa cualquier condición médica relevante",
                        null=True,
                        verbose_name="Condiciones Médicas",
                    ),
                ),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Registro"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Actualización"
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(default=True, verbose_name="Usuario Activo"),
                ),
                (
                    "usuario_django",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario del Sistema",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
                "ordering": ["nombre", "apellido"],
                "indexes": [
                    models.Index(
                        fields=["cedula"], name="usuarios_us_cedula_ca0d1d_idx"
                    ),
                    models.Index(fields=["email"], name="usuarios_us_email_b467c3_idx"),
                    models.Index(
                        fields=["fecha_nacimiento"],
                        name="usuarios_us_fecha_n_6f2751_idx",
                    ),
                ],
            },
        ),
    ]
